# Generated by Django 2.2.2 on 2019-08-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20190731_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='track_no',
            field=models.IntegerField(null=True),
        ),
    ]
