# Generated by Django 2.2.2 on 2019-08-01 08:00

from django.db import migrations, models
import someapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='fil',
            field=models.FileField(null=True, upload_to=someapp.models.get_location),
        ),
    ]
