# Generated by Django 2.2.2 on 2019-08-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0003_comments_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='fil',
        ),
    ]
